config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :offers do
    resources :reviews, only: %i[new create edit update destroy]
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create destroy]
  end

  resources :favorites, only: %i[index]

  resources :bookings, only: %i[index show edit update] do
    member do
      patch :accept
      patch :refuse
      get :payment
      post :success
      patch :cancel
      get :confirmation
    end
  end

  devise_for :users
  resources :users, only: %i[show]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  validates :start_date, :end_date, :number_of_guests, presence: true
  validates :number_of_guests, numericality: { only_integer: true, greater_than: 0 }
  validate :overlapping_dates
  default_scope { order(created_at: :desc) }

  attribute :status, :integer
  enum status: { refused: -2, cancelled: -1, pending: 0, accepted: 1 }

  def duration
    end_date - start_date
  end

  def calculate_total_price
    self.total_price = offer.price_per_night * duration
  end

  def overlapping_dates
    return unless offer

    overlapping = offer.bookings
                       .where.not(id: id)
                       .where.not(status: :cancelled)
                       .where("start_date < ? AND end_date > ?", end_date, start_date
    )

    errors.add(:base, "These dates are already booked") if overlapping.exists?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_offer, only: %i[new create]
  before_action :set_booking, only: %i[show edit update]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @bookings = policy_scope(Booking)
  end

  def show
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.offer = @offer
    @booking.user = current_user

    authorize @booking

    if @booking.save
      redirect_to payment_booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: "Booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def accept
    booking = Booking.find(params[:id])
    authorize booking, :update_status?

    booking.accepted!
    redirect_to bookings_path, notice: "Booking accepted."
  end

  def refuse
    booking = Booking.find(params[:id])
    authorize booking, :update_status?

    booking.refused!
    redirect_to bookings_path, notice: "Booking cancelled."
  end

  def cancel
    booking = Booking.find(params[:id])
    authorize booking, :cancel?

    booking.cancelled!
    redirect_to bookings_path, notice: "Booking cancelled."
  end

  def payment
    @booking = Booking.find(params[:id])
    authorize @booking, :payment?

    @payment_intent = Stripe::PaymentIntent.create(
      amount: @booking.calculate_total_price.to_i,
      currency: 'eur',
      metadata: { booking_id: @booking.id }
    )
  end

  def success
    @booking = Booking.find(params[:id])
    authorize @booking, :success?
    redirect_to confirmation_booking_path(@booking), notice: "Your request to book will be confirmed by a host soon!"
  end

  def confirmation
    @booking = Booking.find(params[:id])
    authorize @booking, :confirmation?
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
    authorize @offer
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :number_of_guests)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/views/bookings/_booking_card.html.erb
<div class="col-md-4 mb-4">
  <div class="card overflow-hidden">
    <div class="position-relative">
      <% if booking.offer.photos.attached? %>

        <%= cl_image_tag booking.offer.photos.first.key,
            transformation: { width: 400, height: 200, crop: "fill" }, alt: "Offer image" %>
        <% else %>
          <div class="card-img-top bg-secondary d-flex align-items-center justify-content-center" style="height: 200px;" >
            <span class="text-white-50">No Image Available</span>
          </div>
      <% end %>
    </div>

    <div class= "card-body p-3">
      <h5 class="card-title"><strong><%= booking.offer.title %></strong></h5>
      <p>
        <i class="fa-solid fa-calendar me-1"></i> From <%= booking.start_date %> &nbsp;&nbsp;
        <i class="fa-solid fa-calendar me-1"></i> To <%= booking.end_date.strftime("%b %d, %Y") %>
      </p>
      <p><i class="fa-solid fa-person me-1"></i> <%= booking.number_of_guests %></p>

      <% if booking.offer.user == current_user %>
        <!-- HOST VIEW -->
        <p><i class="fa-solid fa-user me-1"></i> <%= "#{booking.user.first_name} #{booking.user.last_name}" %></p>
        <p><i class="fa-regular fa-envelope me-1"></i> <%= booking.user.email %></p>

        <% if booking.pending? %>
          <p>Do you want to accept or refuse the booking?</p>
          <div class="d-flex justify-content-center gap-3 my-2">
            <%= button_to "Accept booking", accept_booking_path(booking), method: :patch, class: "btn btn-success booking-btn-success btn-sm", data: { confirm: "Accept this booking?" } %>
            <%= button_to "Refuse booking", refuse_booking_path(booking), method: :patch, class: "btn btn-danger booking-btn-danger btn-sm", data: { confirm: "Refuse this booking?" } %>
          </div>
        <% end %>

      <% else %>
        <!-- GUEST VIEW -->
        <p><i class="fa-solid fa-location-dot me-1"></i> <%= booking.offer.address %></p>
        <p>
          <i class="fa-regular fa-bell me-1"></i>
          <span class="badge bg-secondary mb-2 py-1">
            <%= booking.cancelled? ? "Cancelled" : (booking.status&.capitalize || "Pending") %>
          </span>
        </p>

        <% if booking.accepted? || booking.pending? %>
          <%= form_with url: cancel_booking_path(booking), method: :patch, local: true, data: { turbo_confirm: "Cancel this booking?" } do %>
            <%= submit_tag "Cancel booking", class: "btn btn-warning my-3" %>
          <% end %>
        <% end %>

        <% if booking.cancelled? %>
          <p class="card-text mt-2">This booking was cancelled.</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="form-wrapper mt-4 sticky-top">
  <div class="form">
    <h2 class="form-heading text-center">Book your accomodation today</h2>
    <%= simple_form_for([offer, booking], html: { data: { controller: "price", turbo: false }}) do |f| %>
      <% if booking.errors[:base].any? %>
        <div class="alert alert-danger">
          <% booking.errors[:base].each do |error| %>
            <p><%= error %></p>
          <% end %>
        </div>
      <% end %>
      <div class="form-inputs row justify-content-center">
        <%= f.input :start_date, as: :string, placeholder: "Start date",label: false, input_html: { data: { controller: "flatpickr", action: "input->price#update" } } %>
        <%= f.input :end_date, as: :string, placeholder: "End date",label: false, input_html: { data: { controller: "flatpickr", action: "input->price#update" } } %>
        <%= f.input :number_of_guests, label: false, placeholder: "Number of guests" %>
        <p>Total price: <span data-price-target="total">€0</span></p>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Continue to Payment", class: "shining-button me-2 mt-1" %>
      </div>
    <% end %>
  </div>
</div>

<%# This line is only for JS price per night file %>
<span id="price-per-night" data-price-per-night="<%= offer.price_per_night %>" hidden></span>

app/views/bookings/confirmation.html.erb
<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="text-center p-5 shadow-lg rounded-4" style="max-width: 600px; background-color: #f8f9fa;">
    <h1 class="mb-3" style="font-size: 2.5rem;">🎉 Booking Confirmed!</h1>
    <p class="lead mb-4">
    Thank you, <%= @booking.user.first_name.capitalize %> <%= @booking.user.last_name.capitalize %>!<br>
      Your booking for "<%= @booking.offer.title %>" is confirmed from <strong><%= @booking.start_date %></strong> to <strong><%= @booking.end_date %></strong>.
    </p>

    <hr class="my-4">

    <p class="text-muted">We’ve sent you a confirmation email with all the details.</p>

    <%= link_to "← Back to Home", root_path, class: "btn btn-primary btn-lg mt-3" %>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="banner-edit" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1571459/pexels-photo-1571459.jpeg)">
  <div class="page-header text-center mt-3">
    <h1 class="h4 mb-2"> BOOKING INFORMATION </h1>
    <p>You can edit your booking details below:</p>
  </div>

  <div class="container col-md-3 mb-4">
    <%= simple_form_for [@offer, @booking] do |f| %>
      <%= f.input :start_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
      <%= f.input :end_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
      <%= f.input :number_of_guests %>

      <div class="form-actions">
        <%= f.button :submit, "Update Booking", class: "btn btn-primary" %>
        <%= link_to "Cancel edit", booking_path, class: "btn btn-danger text-white" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="banner-active-booking" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1571459/pexels-photo-1571459.jpeg)">
  <h1 class="text-center mt-4 bookings-title mb-4 ">My Booking History Dashboard</h1>
  <p class="text-center mb-0 description-text fs-5">
      Welcome <%= current_user.first_name%>, here you can view and manage all your current and upcoming bookings with ease.
  </p>
</div>


<div class="container">
  <% active_bookings = @bookings.reject(&:cancelled?) %>
  <% cancelled_bookings = @bookings.select(&:cancelled?) %>

  <% if active_bookings.any? %>
    <h2 class="mt-4 mb-4">Latest Bookings &raquo;</h2>

    <div class="row">
      <% active_bookings.each do |booking| %>
        <% if booking.offer.user == current_user || booking.user == current_user %>
          <%= render partial: "booking_card", locals: { booking: booking, current_user: current_user } %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if cancelled_bookings.any? %>
    <h2 class="mt-4 mb-4 text-muted">Cancelled Bookings &raquo;</h2>
    <div class="row">
      <% cancelled_bookings.each do |booking| %>
        <% if booking.user == current_user %>
          <%= render partial: "booking_card", locals: { booking: booking, current_user: current_user } %>
        <% end %>
      <% end %>
    </div>
  <% end%>

  <div class="container mt-3 text-left">
    <%= link_to "Back to home page", root_path, class: "btn btn-secondary border-2 rounded-3" %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= render 'form', booking: @booking, offer: @offer %>
</div>

app/views/bookings/payment.html.erb
<div class="container mt-4">
  <div class="payment-card">
    <h2 class="payment-card-title">Complete your booking for <%= @booking.offer.title %></h2>
    <h5 class="mt-3">The total price is: <%= number_to_currency(@booking.total_price) %></h5>


      <%= form_with url: success_booking_path(@booking), method: :post,
                      html: { data: {
                        controller: "stripe",
                        stripe_target: "form",
                        stripe_public_key_value: ENV['STRIPE_PUBLISHABLE_KEY'],
                        stripe_client_secret_value: @payment_intent.client_secret,
                        action: "submit->stripe#submit"
                      } } do |f| %>
      <div class="payment-card-content">
        <div data-stripe-target="card" class="my-5"></div>
      </div>

    <%= f.submit "Pay now", data: { stripe_target: "submit" }, class: "payment-card-pay-btn" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>






<%# It is used to edit an existing booking %>
<div class="container">
  <%= link_to "Edit Booking", edit_booking_path, class: "btn btn-primary" %>
  <%= link_to "<< To offers", root_path, class: "btn btn-secondary" %>
</div>