config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :offers do
    resources :reviews, only: %i[new create edit update destroy]
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create destroy]
  end

  resources :favorites, only: %i[index]

  resources :bookings, only: %i[index show edit update] do
    member do
      patch :accept
      patch :refuse
      get :payment
      post :success
      patch :cancel
      get :confirmation
    end
  end

  devise_for :users
  resources :users, only: %i[show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <%= notice %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
  </a>
</div>
<% end %>
<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><strong>Oops!</strong> 😱 a problem has occurred while processing your booking.</span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-4">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github" style="color: black;"></i></a>
    <a href="#"><i class="fab fa-instagram" style="color: #E4405F;"></i></a>
    <a href="#"><i class="fab fa-facebook" style="color: #1877F2;"></i></a>
    <a href="#"><i class="fab fa-twitter" style="color: #1DA1F2;"></i></a>
    <a href="#"><i class="fab fa-linkedin" style="color: #0A66C2;"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if controller_name == "offers" && action_name == "show" %>
            <li class="nav-item mx-2 m-top-2">
              <%= link_to "Book this flat", new_offer_booking_path(offer), class: "simple-button-navbar me-2 mt-1" %>
            </li>
          <% else %>
            <li class="nav-item m-top-2 me-2">
              <%= link_to "New flat", new_offer_path, class: "shining-button" %>
            </li>
          <% end %>



          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "avatar rounded-circle", alt: "dropdown menu", style: "width: 30px; height: 30px;" %>
              <% else %>
                <%= image_tag "default_avatar.png", class: "avatar rounded-circle", alt: "dropdown menu", style: "width: 30px; height: 30px;" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "See Bookings", bookings_path, class: "dropdown-item" %>
              <%# <%= link_to "See Favorites", favorites_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <div class="auth-buttons">
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "signup-button me-2" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "login-button me-2" %>
            </li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>