config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :offers do
    resources :reviews, only: %i[new create edit update destroy]
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create destroy]
  end

  resources :favorites, only: %i[index]

  resources :bookings, only: %i[index show edit update] do
    member do
      patch :accept
      patch :refuse
      get :payment
      post :success
      patch :cancel
      get :confirmation
    end
  end

  devise_for :users
  resources :users, only: %i[show]
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :price_per_night, presence: true, numericality: { only_float: true }
  validates :number_of_bathrooms, :number_of_beds, :guests_limit, numericality: { only_integer: true }

  PROPERTY_TYPES = ["Apartment", "House", "Villa", "Cabin"]
  validates :property_type, inclusion: { in: PROPERTY_TYPES }
  validate :must_have_at_least_one_photo, on: :create

  include PgSearch::Model
  pg_search_scope :search_by_offers,
                  against: %i[title description address],
                  using: {
                    tsearch: { prefix: true }
                  }

  def average_rating
    reviews.average(:rating)&.round(2) || 0
  end

  private

  def must_have_at_least_one_photo
    return if photos.attached?

    errors.add(:photos, "At least a picture must be included")
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_offer, only: %i[show edit update destroy]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    if params[:query].present?
      @offers = policy_scope(Offer).search_by_offers(params[:query])
    else
      @offers = policy_scope(Offer)
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @review = Review.new
    @review.offer = @offer
    @booking = Booking.new
    @booking.offer = @offer
    @reviews = @offer.reviews.includes(:user)
    authorize @offer
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offers_params)
    @offer.user = current_user

    authorize @offer
    if @offer.save
      redirect_to @offer
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @offer
  end

  def update
    authorize @offer
    if params[:offer][:photos].is_a?(Array) && params[:offer][:photos].any? { |p| p.is_a?(ActionDispatch::Http::UploadedFile)}
      @offer.photos.purge
      @offer.photos.attach(params[:offer][:photos])
    end

    if @offer.update(offers_params.except(:photos))
      redirect_to @offer
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @offer

    @offer.destroy
    redirect_to root_path, notice: 'Offer was successfully deleted.'
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offers_params
    params.require(:offer).permit(:title, :address, :description, :price_per_night, :number_of_bathrooms, :number_of_beds,
                                  :guests_limit, :property_type, photos: [])
  end
end

app/views/offers/_form.html.erb
<div class="offers-wrap">
      <div class="container mt-2">
        <%= simple_form_for @offer, html: { multipart: true } do |f| %>
          <%= f.input :title %>
          <%= f.input :description, as: :text, input_html: { rows: 5 } %>
          <%= f.input :address %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_bathrooms %>
          <%= f.input :number_of_beds %>
          <%= f.input :guests_limit %>
          <%= f.input :property_type, collection: Offer::PROPERTY_TYPES, prompt: "Select a property type" %>


          <%= f.input :photos, as: :file, input_html: { multiple: true } %>

          <div class="form-actions mb-2">
            <%= f.button :submit, class: "btn btn-primary me-1" %>
            <%= link_to "Cancel request", root_path, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
</div>

app/views/offers/edit.html.erb
<div class="banner-edit" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg)">
  <h1 class="h4 mb-2">PROPERTY INFORMATION </h1>
  <p class="text-white"> You can edit your property inputs below:</p>
</div>

<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <div class="offer-form">
      <div class="mt-2">
        <%= render "form", offer: @offer %>
      </div>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg)">
  <div class="container">
    <h1>Finding an accomodation made simple!</h1>
    <p>Discover stays that fit your style and budget — from cozy homes to unique experiences — all in just a few clicks.</p>
    <div class="row justify-content-left">
    <div class="col-sm-10">
      <%= form_tag offers_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control me-2",
              placeholder: "Search for a flat"
          %>
        <%= submit_tag "Search", name: "", class: "simple-button" %>
      <% end %>
    </div>
  </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row mt-5">
    <% @offers.each do |offer| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <% if offer.photos.attached? %>
            <div id="carouselOffer<%= offer.id %>" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <% offer.photos.each_with_index do |photo, index| %>
                  <div class="carousel-item <%= 'active' if index == 0 %>">
                    <%= link_to offer_path(offer) do %>
                      <%= cl_image_tag photo.key, transformation: { width: 400, height: 250, crop: "fill" }, class: "d-block w-100" %>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselOffer<%= offer.id %>" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselOffer<%= offer.id %>" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
              </button>
            </div>
          <% end %>


          <div class="card-body">
            <h5 class="card-title"><%= offer.title %></h5>
            <p class="card-text"><%= offer.address %></p>
            <p><strong><%= number_to_currency(offer.price_per_night.to_i,
              precision: offer.price_per_night.to_i == offer.price_per_night ? 0 : 2) %></strong> / night</p>
            <div class="star-rating mb-3">
              <% if offer.reviews.any? %>
                <% 5.times do |i| %>
                  <% if i < offer.average_rating.to_i %>
                    <i class="fas fa-star"></i>
                  <% else %>
                    <i class="far fa-star"></i>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <%= link_to "View", offer_path(offer), class: "simple-button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="offers-wrap">
      <div class="container mt-2">
        <%= simple_form_for @offer, html: { multipart: true } do |f| %>
          <%= f.input :title %>
          <%= f.input :description, as: :text, input_html: { rows: 5 } %>
          <%= f.input :address %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_bathrooms %>
          <%= f.input :number_of_beds %>
          <%= f.input :guests_limit %>
          <%= f.input :property_type, collection: Offer::PROPERTY_TYPES, prompt: "Select a property type" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true, required: true } %>

          <div class="form-actions mb-2">
            <%= f.button :submit, class: "btn btn-primary me-1" %>
            <%= link_to "Cancel request", root_path, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
</div>

app/views/offers/show.html.erb
<div class="container my-4">
  <div class="d-flex justify-content-between align-items-center">
    <h2><%= @offer.title %></h2>

    <div id="favorite-button">
      <% if user_signed_in? %>
        <% if current_user.favorites.none?(offer: @offer) %>
          <%= button_to offer_favorites_path(@offer), method: :post, form: { data: { turbo_stream: true } }, class: "btn p-0 border-0 bg-transparent" do %>
            <i class="fa-regular fa-heart" style="color:red;"></i>
          <% end %>
        <% else %>
          <%= button_to offer_favorites_path(@offer), method: :delete, data: { turbo_method: :delete }, form: { data: { turbo_stream: true } }, class: "btn p-0 border-0 bg-transparent" do %>
            <i class="fa-solid fa-heart" style="color: red;"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row g-2">
    <div class="col-md-6">
      <div class="image-wrapper h-100">
        <% if @offer.photos.attached? %>
          <%= cl_image_tag @offer.photos.first.key, transformation: { height: 600, width: 600, crop: "fill", gravity: "auto" }, class: "img-fluid rounded w-100 h-100 object-fit-cover" %>
        <% end %>
      </div>
    </div>

    <div class="col-md-6 h-75">
      <div class="row g-2">
        <% @offer.photos[1, 4].each_with_index do |photo, index| %>
          <div class="col-6">
            <div class="image-wrapper h-100">
              <%= cl_image_tag photo.key, transformation: { height: 300, width: 300, crop: "fill", gravity: "auto" }, class: "img-fluid w-100 h-100 object-fit-cover image-grid" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 p-0">
        <div class="ms-1">

          <div data-controller="map"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            data-map-marker-value="<%= { lng: @offer.longitude, lat: @offer.latitude }.to_json %>"
            style='width: 100%; height: 300px; border-radius: 12px;'
            class="mt-4 mb-4">
          </div>

          <div class="container-show">
            <h4 class="text-center"><strong> Details of the Flat </strong></h4>
            <p> Address: <%= @offer.address %></p>
            <p> Price per night: <%= @offer.price_per_night %></p>
            <p> Number of beds: <%= @offer.number_of_beds %></p>
            <p> Number of bathroom: <%= @offer.number_of_bathrooms %></p>
          </div>

          <% if @offer.reviews.any? %>
            <div class="star-rating mb-3"> Rating :
                      <% 5.times do |i| %>
                        <% if i < @offer.average_rating.to_i %>
                          <i class="fas fa-star"></i>
                        <% else %>
                          <i class="far fa-star"></i>
                        <% end %>
                      <% end %>
                    </div>
          <% else %>
            <h5 class="mt-4">There are no reviews yet.</h5>
          <% end %>
          <% @offer.reviews.each do |review| %>
            <div class="card p-3 mb-3">
              <div class="d-flex justify-content-between align-items-center mb-1">
                <strong><%= review.user.first_name.capitalize %> <%= review.user.last_name.capitalize %></strong>
                <span class="badge bg-success">Rating: <%= review.rating %>/5</span>
              </div>
              <p class="mb-2"><%= review.comment %></p>

              <% if current_user == review.user %>
                <div class="d-flex gap-2">
                  <%= link_to "Edit", "#", class: "btn btn-outline-primary btn-sm", data: { bs_toggle: "collapse", bs_target: "#edit-review-#{review.id}" } %>
                  <%= button_to "Delete", offer_review_path(@offer, review), method: :delete, onclick: "return confirm('Are you sure you want to delete this review?')", class: "btn btn-outline-danger btn-sm" %>
                </div>

                <div id="edit-review-<%= review.id %>" class="collapse mt-2">
                  <%= simple_form_for [@offer, @review], html: { class: "border rounded p-3" } do |f| %>
                    <%= f.input :rating, label: "Update Rating" %>
                    <%= f.input :comment, label: "Update Comment" %>
                    <%= f.submit "Save changes", class: "btn btn-sm btn-success" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>


          <% if policy(@review).create? && !@offer.reviews.exists?(user: current_user) %>
            <div class="mt-4">
              <h6>Leave a review:</h6>
              <%= simple_form_for [@offer, @review] do |f| %>
                <%= f.input :rating, input_html: { min: 1, max: 5, type: "number" } %>
                <%= f.input :comment %>
                <%= f.submit "Submit review", class: "btn btn-outline-success mt-2" %>
              <% end %>
            </div>
          <% end %>

          <div class="form-actions mb-4 d-flex gap-2">
            <% if policy(@offer).update? %>
              <%= link_to "Edit Offer", edit_offer_path(@offer), class: "btn btn-primary" %>
              <%= button_to "Delete offer", offer_path(@offer),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <% if user_signed_in? %>
          <%= render 'bookings/form', booking: @booking, offer: @offer %>
        <% else %>
          <h4 class="form-heading text-center mt-4" style="position: sticky; top: 30%; z-index: 10;">Please sign up or login in to book this flat</h4>
        <% end %>
      </div>
    </div>
  </div>
</div>